--流程数据定义部分 (删除数据)

DELETE FROM FIXFLOW_DEF_BYTEARRAY; -- 流程定义大字段存储表

DELETE FROM FIXFLOW_DEF_DEPLOYMENT; -- 发布信息表

DELETE FROM FIXFLOW_DEF_PROCESSDEFINITION; -- 流程定义信息表


--流程实例数据部分 (删除数据)

DELETE FROM FIXFLOW_RUN_PROCESSINSTANECE; -- 流程实例表

DELETE FROM FIXFLOW_RUN_TAKSINSTANECE; -- 任务实例表

DELETE FROM FIXFLOW_RUN_TOKEN; -- 流程令牌表

DELETE FROM FIXFLOW_RUN_VARIABLE; -- 流程实例变量表

DELETE FROM FIXFLOW_RUN_TASKIDENTITYLINK ; -- 任务候选人



--流程数据定义部分 (查询数据)

SELECT * FROM FIXFLOW_DEF_BYTEARRAY; -- 流程定义大字段存储表

SELECT * FROM FIXFLOW_DEF_DEPLOYMENT; -- 发布信息表

SELECT * FROM FIXFLOW_DEF_PROCESSDEFINITION; -- 流程定义信息表


--流程实例数据部分 (查询数据)

SELECT * FROM FIXFLOW_RUN_PROCESSINSTANECE; -- 流程实例表

SELECT * FROM FIXFLOW_RUN_TAKSINSTANECE; -- 任务实例表

SELECT * FROM FIXFLOW_RUN_TOKEN; -- 流程令牌表

SELECT * FROM FIXFLOW_RUN_TASKIDENTITYLINK ; --任务候选人

SELECT * FROM FIXFLOW_CONFIG_GROUPINFO; --组配置

SELECT * FROM FIXFLOW_RUN_VARIABLE; --数据变量持久化 

